### ISSUE TITLE
Post-build seedtool regression test script

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/seedtool-cli#33]
I'd love at some point some type of regression-test.sh shell script that would test all of the functionality of seedtool, both with deterministic randonmess, and with true randomness, ideally in some way such that it round-trips in multiple passes to verify its own operations.

This can be derived from the code unit testing, but ideally does more and tests the system as a whole in such as way that it isn't testing the invidual pieces, but the whole using the results of the math to be the confirmation.

**Comment by wolfmcnally** [comment]
Yes, this would be good. Currently I go through all the examples in MANUAL.md when I want to regression test, but a script to do it would be good.

**Comment by wolfmcnally** [comment]
This was implemented some time ago, so closing.
