### ISSUE TITLE
Reproducible build

### ISSUE THREAD

**Issue by secinthenet** [BlockchainCommons/seedtool-cli#48]
https://reproducible-builds.org/

Related to #44

**Comment by wolfmcnally** [comment]
As #44 has been closed, I'm closing this.

**Comment by secinthenet** [comment]
@wolfmcnally this issue is not fixed, please reopen. Docker doesn't guarantee reproducibility, in particular when you run `apt-get` you depend on whatever you're being served.
For real reproducibility, we would need something like Nix or Bazel.

**Comment by wolfmcnally** [comment]
@secinthenet Is this something you intend to offer a PR for?

**Comment by secinthenet** [comment]
Maybe, no guarantees
