### ISSUE TITLE
Error parsing hex input when number of bytes is not divisible by 4

### ISSUE THREAD

**Issue by guiambros** [BlockchainCommons/seedtool-cli#50]
When entering an hex seed input with 14, 18, 22, 26 or 30 bytes, seedtool returns garbage data, or internal error.

Entering any seed with length between 16-32 that is _also divisible by 4 works_ well (i.e., 16, 20, 24, 28, 32).

I guess there's an unbound string checking somewhere, but wasn't able to find in a cursory look at the code.

#### Example

> Seed is 28 hex characters in length == 14 bytes:

```
$ ./src/seedtool --in hex --out bip39 1234567890123456789012345678
pb`

$ ./src/seedtool --in hex --out bip39 1234567890123456789012345678
!vz

$ ./src/seedtool --in hex --out bip39 1234567890123456789012345678
./src/seedtool: An internal error occurred.
```

> Seed is 32 hex characters == 16 bytes:

```
$ ./src/seedtool --in hex --out bip39 12345678901234567890123456789012
banana pencil owner cage cash clinic time across crowd record catch caution
```

**Comment by wolfmcnally** [comment]
Thanks for reporting this. Even if seedtool throws an error it should never be an internal error or garbage output. I'll look into it.

**Comment by wolfmcnally** [comment]
OK, the problem appears to be that I validated the input for BIP39 conversion incorrectly. The [BIP39 docs state](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic) that the seed length must be in increments of 32 bits, i.e., divisible by 4. So lengths like 14 are in fact invalid and Seedtool should have caught and reported this.
