### ISSUE TITLE
Allow BIP39 <-> SSKR

### ISSUE THREAD

**Issue by ensingerphilipp** [BlockchainCommons/seedtool-cli#52]
Why not allow input of bip-39 and output of sskr (and vice versa)?

SSKR seems to be the best option right now to use a somewhat standardized format for shamir secrets that is not company dependent like Trezors SLIP-39.

It would be helpful to allow conversion form bip-39 to sskr as now i have to take the extra step of converting to HEX manually first.

**Comment by ksedgwic** [comment]
This seems useful to me.

**Comment by wolfmcnally** [comment]
The architecture of seedtool is specifically designed to do a single conversion per invocation. More complex conversions are accomplished by multiple invocations. This is by design to keep seedtool from becoming too complex.
